name: Pull request master

on:
  pull_request:
    branches: [master]

jobs:
  python3_tests:
    uses: ./.github/workflows/test-python.yml

  python2_tests:
    uses: ./.github/workflows/test-python-py2.yml
