name: Push master

on:
  push:
    branches: [master]

jobs:
  python3_tests:
    uses: ./.github/workflows/test-python.yml

  bump_version:
    needs: python3_tests
    uses: ./.github/workflows/bump-and-publish.yml
    secrets: inherit
